### ISSUE TITLE
Errors when running wally-ui

### ISSUE THREAD

**Issue by lonnietc** [nylar/wally-ui#1]
Greetings, 

I am trying to set up wally-ui to do some simple testing with rethinkdb but am getting some errors and I do not know why.

spartan:~/work/wally-ui$ go build
# github.com/nylar/wally

src/github.com/nylar/wally/indexer.go:204: undefined: gorethink.Db
src/github.com/nylar/wally/indexer.go:234: undefined: gorethink.Db
src/github.com/nylar/wally/indexer.go:244: undefined: gorethink.Db
src/github.com/nylar/wally/search.go:25: undefined: gorethink.Db
src/github.com/nylar/wally/search.go:56: undefined: gorethink.Db
src/github.com/nylar/wally/utils.go:25: undefined: gorethink.Db
src/github.com/nylar/wally/utils.go:26: undefined: gorethink.Db
src/github.com/nylar/wally/utils.go:27: undefined: gorethink.Db
src/github.com/nylar/wally/utils.go:28: undefined: gorethink.Db
src/github.com/nylar/wally/utils.go:28: too many errors

I have rethingdb installed on my ubuntu 15.04 system and then created the "wally" database and tables in the config yml file:

database:
  host: localhost:28015
  name: wally
tables:
  document_table: documents
  index_table: indexes

but still things do not work for some reason.

Can you please help?

Thanks,
Lonnie

**Comment by nylar** [comment]
Hello Lonnie,

There seems to have been a backwards incompatible change made to gorethinkdb where a function was renamed (https://godoc.org/github.com/dancannon/gorethink#DB). This has just been fixed in [wally](https://github.com/nylar/wally), so if you go get the latest version of that it should now work:

``` shell
go get -u -v github.com/nylar/wally
```

If it doesn't work, please let me know and thank you for bringing this to my attention.

Regards,
Scott

**Comment by lonnietc** [comment]
Hi Scott,

I think that it I got part of it working and the search page came up on on port 8008 which was in the main.go file after getting the wally-ui and running to main.go file from there.

I am a bit new to rethinkdb, but what I did was to create a database "wally" and then 2 tables, (documents, indexes) from the rethinkdb web interface. 

As there is no index data in the tables, when I typed in the "go" in the wally search input line, I get:

gorethink: Index `word` was not found on table `wally.indexes`. in: 
r.DB("wally").Table("indexes").GetAll(r.Args(["go"]), index="word").EqJoin("document_id", r.DB("wally").Table("documents")).Zip().OrderBy(r.Desc("count")).Slice(0, 2)

So then how can I get a couple of items in the index and documents tables so that I can just return a few line items as I want to work with setting up and modifying the files in the templates directory?

thanks again
Lonnie

**Comment by nylar** [comment]
Hi Lonnie,

A good way to setup the data initially is to run https://godoc.org/github.com/nylar/wally#DatabaseRebuild, this will setup the tables and the indexes for you. So you could just edit main.go in the main function to run that before anything else just once and then remove it so it doesn't remove your data on the next run of the application.

In order to get data in, you need to run the wally CLI from github.com/nylar/wally/cli/wally. You can build it with go build which will produce the binary, you can then crawl a webpage with:

``` shell
./wally crawl -url="http://bbc.co.uk"
```

To be honest though, this repo hasn't been maintained for a long time (should have marked it as deprecated), instead I built https://github.com/nylar/miru which does recursive crawling and other stuff (accompanying UI here - https://github.com/nylar/miru-admin). Might be worth looking there instead. :)

Happy to answer any other questions you have.

Regards,
Scott.

**Comment by lonnietc** [comment]
Thanks again for getting back to me. I actually did set up the cli as well and with the information that you provided, I was able to crawl a few sites for which the rethinkdb show some indexes and document are in there, but I just cannot see what to query on as I am getting "No results found" each time.

I tried in the cli:

./wally search "go"

and a few other variations and other searches, but still the same results. Is there a special format for the search?

I  would like to get wally running first and then I will move on  to look at the miru as you suggest, ok.

Cheers and thanks again,
Lonnie

**Comment by lonnietc** [comment]
Scott,

I was able to get some data into Rethikdb via the cli now and do a search using the wally-ui.

Cheers,
Lonnie

**Comment by nylar** [comment]
One way you can figure out what you have indexed is by going to the rethinkdb admin console (it is set to port :8080 by default) and going to the data explorer. From there you can run:

``` javascript
r.db('wally').table('documents')
```

Which will list all of the sites that you have crawled, you can choose a word from there and the search should locate all documents where that word is present (bear in mind that this includes stop words which are stripped out of the indexer and thus won't be searchable). Alternatively, you can run the following from the same area:

``` javascript
r.db('wally').table('indexes')
```

This will produce a list of all words that have been indexed by Wally, any of these should yield results in the UI for Wally. I should note that your CLI call to search is slightly incorrect, although that isn't your fault as it is confusing. You should instead do, which will yield the same results as you would get in the UI:

``` shell
./wally search -query="go"
```

Hope that helps,
Scott.

**Comment by nylar** [comment]
Excellent! Closing the issue, please create a new ticket if you encounter any other issues. :smiley: 

Scott.

**Comment by lonnietc** [comment]
Thanks again as this was what I need to know.

I will look at the miru, but what drew me to wally was the use of your templates as well.

Cheers,
Lonnie
